# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "frisk-backend"
  tags:
  - "internal"
spec:
  type: "service"
  lifecycle: "production"
  owner: "skvis"
  system: "sikkerhetsmetrikker"
  providesApis:
  - "frisk-backend-api"
---
apiVersion: "backstage.io/v1alpha1"
kind: "API"
metadata:
  name: "frisk-backend-api"
  tags:
  - "internal"
spec:
  type: "openapi"
  lifecycle: "production"
  owner: "skvis"
  definition: |
    openapi: "3.0.0"
    info:
        title: frisk-backend API
    paths:
